### ISSUE TITLE
How to convert type of column from string to float ?

### ISSUE THREAD

**Issue by devasyadave** [westandskif/convtools#23]
How to convert type of column from string to float ?
I want to compare a column to float in the Table.from_csv().filter() but the column type is getting detected as string and then throws error 
TypeError: '<=' not supported between instances of 'str' and 'float'

from convtools import conversion as c
from convtools.contrib.tables import Table

rows = (
    Table.from_csv("Coordinates.csv", header=True)
    .filter(c.col("lat") <= 35.674521).filter(c.col("lat") >= 8.06890)
    .filter(c.col("lon") >= 68.1941).filter(c.col("lon") <= 97.39564)
    .into_csv("tmp-updated.csv")
)

**Comment by westandskif** [comment]
> but the column type is getting detected as string

Yeah, `Table` doesn't make any assumptions about types, it just reads the data just like `csv.reader` does, that's why everything is a string.

`update` should allow to update your columns like this:
```python
from convtools import conversion as c
from convtools.contrib.tables import Table

rows = (
    Table.from_csv("Coordinates.csv", header=True)
    .update(
        lat=c.col("lat").as_type(float),
        lon=c.col("lon").as_type(float),

        # # OR THE SAME, BUT DYNAMICALLY:
        # **{column_name: c.col(column_name) for column_name in ("lat", "lon")},
    )
    .filter(
        c.and_(
            c.col("lat") <= 35.674521,
            c.col("lat") >= 8.06890,
            c.col("lon") >= 68.1941,
            c.col("lon") <= 97.39564,
        )
    )
    .into_csv("tmp-updated.csv")
)
```

or if you want to keep columns as strings, but still compare, you can do type casting during comparisons, but this will lead to casting to float twice per field in your case, e.g.:
```python
rows = (
    Table.from_csv("Coordinates.csv", header=True)
    .filter(
        c.and_(
            c.col("lat").as_type(float) <= 35.674521,
            c.col("lat").as_type(float) >= 8.06890,
            c.col("lon").as_type(float) >= 68.1941,
            c.col("lon").as_type(float) <= 97.39564,
        )
    )
    .into_csv("tmp-updated.csv")
)
```

**Comment by westandskif** [comment]
Should you have any questions, please let me know.
